# Generated by Django 2.0.5 on 2018-05-22 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=350)),
                ('author', models.CharField(max_length=350)),
                ('pub_year', models.SmallIntegerField()),
                ('publisher', models.CharField(max_length=350)),
                ('img_s', models.URLField(max_length=350, validators=[django.core.validators.URLValidator])),
                ('img_m', models.URLField(max_length=350, validators=[django.core.validators.URLValidator])),
                ('img_l', models.URLField(max_length=350, validators=[django.core.validators.URLValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.Book')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('version', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.BinaryField()),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
    ]
