"""empty message

Revision ID: aec932bc7ced
Revises:
Create Date: 2017-12-06 18:27:01.550684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aec932bc7ced'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('users', sa.Column('email', sa.String(length=60), nullable=True))
	op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
	op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_users_email'), table_name='users')
	# ### end Alembic commands ###
